### ISSUE TITLE
FNet: Mixing Tokens with Fourier Transforms

### ISSUE THREAD

**Issue by etienne87** [fawazsammani/awesome-mlp-mixer#1]
FNet: Mixing Tokens with Fourier Transforms https://arxiv.org/abs/2105.03824 
Does FNet belong? After all, DCT can be implemented (and is on TPUs) in one matrix-multiplication accross patch-dimension.

**Comment by fawazsammani** [comment]
Thanks for letting me know. It seems that this paper came around the same time as MLP mixer....It is very relevant.
I've added it to the list
