### ISSUE TITLE
Suggesting the pNLP-Mixer

### ISSUE THREAD

**Issue by fuscof** [fawazsammani/awesome-mlp-mixer#7]
Hi, we published a while a go this paper as well:
- [pNLP-Mixer: an Efficient all-MLP Architecture for Language](https://aclanthology.org/2023.acl-industry.6/) [[pdf]](https://aclanthology.org/2023.acl-industry.6.pdf)  [[code(unofficial impl.)]](https://github.com/maum-ai/pnlp-mixer)

**Comment by fawazsammani** [comment]
Thanks a lot for letting me know and for your contribution! Already added :)
